### ISSUE TITLE
Board outline file for One circuit board

### ISSUE THREAD

**Issue by sorvis** [HestiaPi/hestia-touch-pcb-dev#2]
Hello,

I tried uploading the Gerbal zip for the One board to oshpark, but it complains "I can't find a board outline file. "

https://oshpark.com/uploads/Jsue3I1o

Would it be possible to add that missing file or perhaps the kicad project? I noticed that the kicad project file works with their software for the other board.

Thank you

**Comment by gulliverrr** [comment]
This is not done via KiCAD. I think Fritzing names ones of the needed layers with a different extension.
My suggestion would be to download the zip file, extract it, rename ONE_contour.gml to ONE_contour.GKO (or ONE_contour.gko), re-zip it and try uploading again. 
Please report here if it worked

**Comment by sorvis** [comment]
Thank you for the quick reply @gulliverrr  I renamed it to ONE_contour.GKO  and it did work just fine!

**Comment by gulliverrr** [comment]
Just to mention... I think this difference of Fritzing is not blocking all PCB houses. Some don't complain and process the zip file fine. Since that repository commit, we have moved far from Fritzing as this was our first beginner tool that got us into PCB design.
Glad you got it working

**Comment by sorvis** [comment]
Curious if that's an older file that you all created are the newer files in another repository? It looks like the ONE folder was the most recent in this repro.

**Comment by gulliverrr** [comment]
No, that would be the latest `released` version. As this project is always progressing, yes there are modifications pending to be either tested or accompanied by the rest of the code, casing, electronics and/or documentation. You are using the right file, for now.
